<!DOCTYPE html>
<html>
    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">  
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="style.css">
    </head>
    
    <body>
        <header>
            
        </header>
        
        <main class="container">
            <div class="col-g">
                <h1>Informations</h1>
                <div class="informations item">
                    <dl>
                        <dt>Contact</dt>
                        <dt>Email</dt>
                        <dd>m@m.com</dd>
                        <dt>Téléphone</dt>
                        <dd>00112233</dd>
                        <dt>LinkedIn</dt>
                        <dd>http.com</dd>
                        <dt>GitHub</dt>
                        <dd>http.com</dd>
                        <dt>Biographie</dt>
                        <ul>Loisirs
                            <li>abc</li>
                            <li>abc</li>
                            <li>abc</li>
                            <li>abc</li>
                            <li>abc</li>
                        </ul>
                    </dl> 
                </div>
            </div>
            <div class="col-d">
                <h1>Compétences</h1>
                <dl>
                    <ul>Langages de Programmation
                        <li>abc</li>
                        <li>abc</li>
                        <li>abc</li>
                        <li>abc</li>
                        <li>abc</li>
                    </ul>
                    <ul>Frameworks & Librairies
                        <li>abc</li>
                        <li>abc</li>
                        <li>abc</li>
                        <li>abc</li>
                    </ul>
                    <ul>Logiciels
                        <li>abc</li>
                        <li>abc</li>
                        <li>abc</li>
                        <li>abc</li>
                    </ul>
                    <ul>Langues
                        <li>abc</li>
                        <li>abc</li>
                        <li>abc</li>
                        <li>abc</li>
                    </ul>
                </dl>
            </div>
        </main>
    </body>
    
</html>